# Generated by Django 4.2.16 on 2024-12-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegi', '0003_receipe_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipe',
            old_name='price',
            new_name='recipe_price',
        ),
    ]
